apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
  annotations:
    configmanagement.gke.io/cluster-selector: select-istio-enable
spec:
  peers:
  - mtls: {}
