apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: belgium
  git:
    syncRepo: git@github.com:<GITHUB-USERNAME>/csp-config-management.git
    syncBranch: master
    secretType: ssh
    policyDir: "docs/locality-specific-policy/"
