apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: taiwan
  git:
    syncRepo: git@github.com:<GITHUB-USERNAME>/csp-config-management.git
    syncBranch: master
    secretType: ssh
    policyDir: "locality-specific-policy/config-root"
