kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team1-admin
subjects:
- kind: User
  name: user2@mycorp.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io